definitions:
  models.Employee:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      join_date:
        type: string
      name:
        type: string
      position:
        type: string
      salary:
        type: number
      updated_at:
        type: string
    required:
    - email
    - name
    - position
    - salary
    type: object
info:
  contact: {}
paths:
  /employees:
    get:
      consumes:
      - application/json
      description: Retrieves all employees from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Employee'
            type: array
        "500":
          description: Error response
          schema:
            additionalProperties: true
            type: object
      summary: Get all employees
      tags:
      - employees
    post:
      consumes:
      - application/json
      description: Creates a new employee record
      parameters:
      - description: Employee object
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Invalid request data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error response
          schema:
            additionalProperties: true
            type: object
      summary: Create employee
      tags:
      - employees
  /employees/{id}:
    delete:
      consumes:
      - application/json
      description: Removes an employee from the database
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid employee ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error response
          schema:
            additionalProperties: true
            type: object
      summary: Delete employee
      tags:
      - employees
    get:
      consumes:
      - application/json
      description: Retrieves a specific employee by their ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Invalid employee ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Employee not found
          schema:
            additionalProperties: true
            type: object
      summary: Get employee by ID
      tags:
      - employees
    put:
      consumes:
      - application/json
      description: Updates an existing employee record
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated employee object
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Invalid employee ID or request data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error response
          schema:
            additionalProperties: true
            type: object
      summary: Update employee
      tags:
      - employees
swagger: "2.0"
